config/routes.rb
Rails.application.routes.draw do
  get 'diversification/index'
  get 'search/index'
  devise_for :users


  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  #Dashboard route
  get "dashboard", to: "dashboard#index"
  post "dashboard", to: "dashboard#create"
  post "update_stock", to: "dashboard#update_stock"
  post "delete_stock", to: "dashboard#delete_stock"
  post "delete_portfolio", to: "dashboard#delete_portfolio"



  get "search", to: "search#index"
  get "search/results", to: "search#index"

  #Add a stock
  post "new_holding", to: "search#add_stock"

  #Diversification
  get "portfoliostats", to: "portfoliostats#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user_custom!
  def index
    @UserIsSignedIn= user_signed_in?

    #Grabs the portfolio of the user
    @portfolio_of_user = Portfolio.where(user_id: current_user.id)

    # This will contain the stock data for the selected portfolio.
    @selectedPortfolio = nil

    #Grabs the stock data for the selected portfolio
    if !params[:portfolio_id].nil?
      @selectedPortfolio = PortfolioStock.includes(:payment_schedule).where(portfolio_id: params[:portfolio_id]).all
    end

  end

  def create
    #Creates a new portfolio of the user if it does not exist
    if Portfolio.where(user_id: current_user.id, portfolio_name: params[:portfolio_name]).empty?
      new_portfolio = Portfolio.new(portfolio_name: params[:portfolio_name], user_id: current_user.id)
      new_portfolio.save

      update_portfolio

    else
      flash[:alert] = "Portfolio already exists"
      redirect_back(fallback_location: dashboard_path)
    end
  end

  # Updates and modifies the stock
  def update_stock
    update_token

    #Fetch new stock data from questrade
    stock_information = Faraday.new(url: "#{Token.find_by(user_id: current_user.id).api_server}v1/symbols?ids=#{PortfolioStock.find(params[:holdingIdModify]).symbol_id}") do |build|
         build.request :authorization, 'Bearer', -> {Token.find_by(user_id: current_user.id).access_token}
         build.response :raise_error
    end

    stock_response = stock_information.get
    stocks_information = JSON.parse(stock_response.body)


    # Determines what type of calculation needed for the total dividends
    def determine_payment_schedule(schedule)
      distribution = 0
      if "Annual" == schedule
        distribution = 1
      elsif "Semi-Annual" == schedule
        distribution = 2
      elsif "Quarterly" == schedule
        distribution = 4
      elsif "Monthly" == schedule
        distribution = 12
      end

      return distribution
    end

    paid = determine_payment_schedule(PortfolioStock.includes(:payment_schedule).find(params[:holdingIdModify]).payment_schedule.distribution_schedule).to_i

    #input new number of shares to the portfolio
    modify_stock = PortfolioStock.find_by(portfolio_id: params[:portfolio_id], id: params[:holdingIdModify]).update(
      portfolio_id: params[:portfolio_id].to_i,
      number_of_shares: params[:number_of_shares].to_i,
      share_price: stocks_information["symbols"][0]["prevDayClosePrice"].to_f,
      avg_share_price: params[:price].to_f,
      total_value: (params[:number_of_shares].to_f * stocks_information["symbols"][0]["prevDayClosePrice"].to_f),
      div_yield: stocks_information["symbols"][0]["yield"].to_f,
      div_per_share: stocks_information["symbols"][0]["dividend"].to_f,
      total_div: (params[:number_of_shares].to_f * stocks_information["symbols"][0]["dividend"].to_f) * paid.to_f,
      industry: stocks_information["symbols"][0]["industrySector"],
        ex_dividend: stocks_information["symbols"][0]["dividendDate"],
      symbol_id: stocks_information["symbols"][0]["symbolId"]
      )
  end

  #Deletes the stock from portfolio
  def delete_stock
    update_token
    PortfolioStock.find_by(portfolio_id: params[:portfolio_id], id: params[:holdingIdDelete]).destroy

    #Refreshes the webpage
    redirect_to request.referer
  end

  #Deletes portfolio
  def delete_portfolio
    Portfolio.find_by(id: params[:portfolio_id]).destroy
    #Refreshes the webpage
    redirect_to dashboard_path
  end

  #Updates the portfolio turtbostream to the template update_target
  def update_portfolio
    respond_to do |format|
      format.turbo_stream { render "dashboard/update_target", locals: { portfolio: Portfolio.where(user_id: current_user.id) }}
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_portfolios.erb
<%# Uses the passed variable "portfolios" and creates the buttons of each entry %>
<% portfolios.each do |f|  %>

    <%if params[:portfolio_id].to_s == f.id.to_s %>
        <%= link_to "#{f.portfolio_name}", dashboard_path(portfolio_id:  f.id), role:"tab", class:"tab tab-active"%>
    <%else%>
        <%= link_to "#{f.portfolio_name}", dashboard_path(portfolio_id:  f.id), role:"tab", class:"tab"  %>
    <%end%>
<%end%>

app/views/dashboard/_stocks.html.erb
<%# Provides the table of stocks %>

<div id="Table" class="mb-[5rem]">
  <%# Modify Dialog %>
  <dialog id="modify_stock" class="modal">
      <div class="modal-box w-11/12 bg-base-300 p-3">
        <h3 class="font-bold text-lg">New Portfolio</h3>
         <%= form_with url: "/update_stock", method: :post, remote: true, class: "grid grid-cols-1 w-full" do |f| %>
            <%= f.label :number_of_shares, "Number of Shares"%>
            <%= f.number_field :number_of_shares, required: true, class: "input input-bordered w-full " %>
            <%= f.label :price, "Price per Share" %>
            <%= f.number_field :price, step: 0.01, required: true, class: "input input-bordered w-full mb-4"%>
            <%= f.hidden_field :portfolio_id, value: params[:portfolio_id]%>
            <%= f.hidden_field :holdingIdModify%>
            <%= f.submit "Add", class:"btn"%>
          <%end%>
        <div class="modal-action">
          <form method="dialog">
            <!-- if there is a button, it will close the modal -->
            <button class="btn">Close</button>
          </form>
        </div>
      </div>
      <!---Exits if clicked outside or pressed 'ESC'--->
      <form method="dialog" class="modal-backdrop">
        <button>close</button>
      </form>
  </dialog>

  <%# Delete stock Dialog %>
  <dialog id="delete_stock" class="modal">
      <div class="modal-box w-11/12 bg-base-300 p-3">
        <h3 class="font-bold text-lg">Delete Stock</h3>
        <p>Are you sure you want to delete this stock?</p>
        <div class="modal-action">
          <form method="dialog">
            <button class="btn">Cancel</button>
          </form>
          <%# Confirm Deletion %>
          <%= form_with url: "/delete_stock", method: :post, remote: true do |f| %>
            <%= f.hidden_field :portfolio_id, value: params[:portfolio_id]%>
            <%= f.hidden_field :holdingIdDelete%>
            <%= f.submit "Confirm", class:"btn btn-warning"%>
          <%end%>
        </div>
      </div>
      <!---Exits if clicked outside or pressed 'ESC'--->
      <form method="dialog" class="modal-backdrop">
        <button>close</button>
      </form>
  </dialog>

  <div class="overflow-x-auto">
    <table class="table">
      <!-- head -->
      <thead>
        <tr>
          <th>Name</th>
          <th> # Shares</th>
          <th>Price</th>
          <th>AVG Share price</th>
          <th>Total Value</th>
          <th>Payout Schedule</th>
          <th>Div Yield</th>
          <th>Div per share</th>
          <th>Total Div</th>
        </tr>
      </thead>
      <tbody>
        <% stocks.each do |stock|%>
          <tr class="hover">
            <th><%=stock.stock_name%></th>
            <td><%=stock.number_of_shares%></td>
            <td>$<%=stock.share_price.round(2)%></td>
            <td>$<%=stock.avg_share_price.round(2)%></td>
            <td>$<%=stock.total_value.round(2)%></td>
            <td><%=stock.payment_schedule.distribution_schedule%></td>
            <td><%=stock.div_yield%>%</td>
            <td>$<%=stock.div_per_share.round(2)%></td>
            <td>$<%=stock.total_div.round(2)%></td>
            <td>
              <%# Will contain Add button%>
              <%# Uses js to change form default values %>
              <button class="btn mr-[15px]" onclick="modify_stock.showModal(), document.getElementById('number_of_shares').value = '<%=stock.number_of_shares%>',document.getElementById('price').value =  '<%=stock.share_price%>', document.getElementById('holdingIdModify').value = '<%=stock.id%>'">modify</button>
              <button class="btn mr-[15px]" onclick="delete_stock.showModal(), document.getElementById('holdingIdDelete').value = '<%=stock.id%>'">delete</button>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboard/index.html.erb
<div>
  <%# Create new portfolio %>
  <dialog id="create_portfolio" class="modal">
      <div class="modal-box w-11/12 bg-base-300 p-3">
        <h3 class="font-bold text-lg">New Portfolio</h3>
        <%= form_with model: @portfolio, method: :post do |f| %>
            <%= f.text_field :portfolio_name, class: "input input-bordered w-full max-w-xs", required: true%>
            <%= f.submit "Add", class:"btn"%>
        <%end%>
        <div class="modal-action">
          <form method="dialog">
            <!-- if there is a button, it will close the modal -->
            <button class="btn">Close</button>
          </form>
        </div>
      </div>
      <!---Exits if clicked outside or pressed 'ESC'--->
      <form method="dialog" class="modal-backdrop">
        <button>close</button>
      </form>
  </dialog>
  <%# Delete Current Portfolio %>
  <dialog id="delete_portfolio" class="modal">
      <div class="modal-box w-11/12 bg-base-300 p-3">
        <h3 class="font-bold text-lg">Delete portfolio</h3>
        <p>Are you sure you want to delete this portfolio?</p>
        <div class="modal-action">
          <form method="dialog">
            <button class="btn">Cancel</button>
          </form>
          <%# Confirm Deletion %>
          <%= form_with url: "/delete_portfolio", method: :post, remote: true do |f| %>
            <%= f.hidden_field :portfolio_id, value: params[:portfolio_id]%>
            <%= f.submit "Confirm", class:"btn btn-warning"%>
          <%end%>
        </div>
      </div>
      <!---Exits if clicked outside or pressed 'ESC'--->
      <form method="dialog" class="modal-backdrop">
        <button>close</button>
      </form>
  </dialog>
  
  <!---Flash message--->
   <% if flash.now[:message] %>
    <div class="alert alert-error bg-error alert-dismissible fade show">
      <%= flash[:message] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <div id="SearchBar" class="flex md:w-[40%] md:space-around w-auto">
    <!---Search button --->
    <%= button_to "Add Holding", search_path, method: :get, class:"btn" %>
    <button class="btn" onclick="create_portfolio.showModal()">New Portfolio</button>
    <%# Connect to Questrade %>
    <%= button_to "Connect to Questrade", "https://login.questrade.com/oauth2/authorize?client_id=YTGdFwCpGjB76WxOJAmmBOem0n1QvA&response_type=code&redirect_uri=https://div-tracker-tjzx7q7eeq-uc.a.run.app", class:"btn btn-primary"%>
    
    
    <%# Delete Portfolio %>
    <%if params[:portfolio_id].present?%>
      <%# Redirct to stats page %>
      <%= button_to "Portfolio Stats", portfoliostats_path, method: :get,params: { portfolio_id: params[:portfolio_id] }, class:"btn" %>
      <button class="btn mr-[15px]" onclick="delete_portfolio.showModal()">Delete Portfolio</button>
    <%end%>
    
  </div>
  <%# Portfolios will be displayed here and navigation will take place here as well%>
  <div>
    <div id="testing" role="tablist" class="tabs tabs-bordered w-fit flex">
      <!-- Turbo frame appears here -->
      <%# Passes the portfolio_of_user variable from the controller to the portfolios partial as a variable called "portfolios" %>
      <%= render "dashboard/portfolios", portfolios: @portfolio_of_user%>
    </div>
  </div>

  <%# Displays the results of each portfolio%>
  <% if params[:portfolio_id].present?%>
    <%= render "stocks", stocks: @selectedPortfolio%>
    <%else%>
    <p>Select a portfolio or create a portfolio</p>
  <%end%>

</div>

app/views/dashboard/update_target.turbo_stream.erb
<%= turbo_stream.update "testing" do %>
  <%= render "dashboard/portfolios", portfolios: portfolio%>
<% end %>