config/routes.rb
Rails.application.routes.draw do
  get 'diversification/index'
  get 'search/index'
  devise_for :users


  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  #Dashboard route
  get "dashboard", to: "dashboard#index"
  post "dashboard", to: "dashboard#create"
  post "update_stock", to: "dashboard#update_stock"
  post "delete_stock", to: "dashboard#delete_stock"
  post "delete_portfolio", to: "dashboard#delete_portfolio"



  get "search", to: "search#index"
  get "search/results", to: "search#index"

  #Add a stock
  post "new_holding", to: "search#add_stock"

  #Diversification
  get "portfoliostats", to: "portfoliostats#index"
end

app/views/layouts/_footer.html.erb
<footer class="footer footer-center p-4 bg-base-300 text-base-content fixed inset-x-0 bottom-0">
  <aside>
    <p>Created by: Samuel Ferrer</p>
  </aside>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar bg-base-300 w-full">
  
  <div class="navbar-start">
   
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
      </div>
      <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
        <% if @UserIsSignedIn%>
          <li><%= link_to "Dashboard", dashboard_path %></li>
        <% else%>
        <li><a>Feedback (To be implemented)</a></li>
        <%end%>
        
      </ul>
    </div>
    <%= link_to "DivTracker", root_path, class:"btn btn-ghost text-xl"%>
  </div>
  <div class="navbar-center hidden lg:flex">
    <ul class="menu menu-horizontal px-1">
      <% if @UserIsSignedIn%>
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <%else%>
          <li><a>Feedback (To be implemented)</a></li>
      <%end%>
    </ul>
  </div>
  <div class="navbar-end", data-controller="theme">
    <%# Theme controller %>
    <label class="swap swap-rotate">
      <!-- this hidden checkbox controls the state -->
      <input type="checkbox" id="themeController"class="opacity-0 theme-controller" data-action="click->theme#update"/>
      <!-- sun icon -->
      <svg class="swap-on fill-current w-8 h-8" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z"/></svg>
      <!-- moon icon -->
      <svg class="swap-off fill-current w-8 h-8" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z"/></svg>
    </label>
    <% if @UserIsSignedIn%>
      <%= button_to "Sign Out", destroy_user_session_path, :method => 'delete', data:{turbo: "false"} %>
    <%else%>
    <button class="btn mr-[15px]" onclick="login.showModal()">Login</button>
    <dialog id="login" class="modal">
      <div class="modal-box w-11/12 bg-base-300 p-3">
        <h3 class="font-bold text-lg">Login</h3>
        
        <%= render "devise/sessions/new"%>
        <div class="modal-action">
          <form method="dialog">
            <!-- if there is a button, it will close the modal -->
            <button class="btn">Close</button>
          </form>
        </div>
      </div>
      <!---Exits if clicked outside or pressed 'ESC'--->
      <form method="dialog" class="modal-backdrop">
        <button>close</button>
      </form>
    </dialog>
    <!---Sign-up Button--->
    <button class="btn" onclick="signup.showModal()">Sign Up</button>
    <dialog id="signup" class="modal">
      <div class="modal-box w-11/12 bg-base-300 p-3">
        <h3 class="font-bold text-lg">Sign Up</h3>
       <%= render "devise/registrations/new"%>
        <div class="modal-action">
          <form method="dialog">
            <!-- if there is a button, it will close the modal -->
            <button class="btn">Close</button>
          </form>
        </div>
      </div>
      <!---Exits if clicked outside or pressed 'ESC'--->
      <form method="dialog" class="modal-backdrop">
        <button>Close</button>
      </form>
    </dialog>
    <%end%>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="dark"> 
  <head>
    <title>DivTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag  "tailwind", "inter-font", "data-turbo-track": "reload", as:"style" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= render "layouts/navbar" %>
      <main class="container mx-auto mt-28 px-5 border-none">
         <p class="notice"><%= notice %></p>

          <p class="alert border-0 bg-base-100"><%= alert  %></p>
          
        <%= yield %>
        
      </main>
    <%= render "layouts/footer" %>
    
  </body>
</html>